### ISSUE TITLE
price_bandit_loop error

### ISSUE THREAD

**Issue by cryptovestor21** [semiotic-ai/autoagora#19]
Running against indexer-service v 0.20.3, I am seeing the following error occasionally in the logs for autoagora:

```
2022-10-25 15:14:19,927 - root - ERROR - price_bandit_loop error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/autoagora/price_multiplier.py", line 83, in price_bandit_loop
    queries_per_second = await environment.queries_per_second(60)
  File "/usr/local/lib/python3.8/site-packages/autoagora/subgraph_wrapper.py", line 33, in queries_per_second
    query_count_1 = await subgraph_query_count(self.subgraph)
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/autoagora/query_metrics.py", line 60, in subgraph_query_count
    assert response.status == 200
AssertionError
```

This is amongst a whole lot of `Training agent. Please wait...` and seems to happen on a recurring basis. I can also see that models are being modified, and some of the graphs on the AA dashboard are populating (spike in QPS correlates with AA being integrated into the Graph stack):

<img width="930" alt="image" src="https://user-images.githubusercontent.com/59484786/197814640-4c32263d-34cb-4776-a98a-90bcb46df8b1.png">

Including current models for reference.

[getAllmodels.log](https://github.com/semiotic-ai/autoagora/files/9861690/getAllmodels.log)

**Comment by aasseman** [comment]
The indexer-service's prometheus endpoint didn't answer with HTTP code 200. I would think that this either a networking problem or a bug in indexer-service.

I will think about a way to have AA react more smoothly to that situation without messing with the AI.

**Comment by aasseman** [comment]
I'm fairly certain that https://github.com/semiotic-ai/autoagora/releases/tag/v0.5.2 will fix it.

**Comment by cryptovestor21** [comment]
With `0.5.2` the old error has been replaced by a new http404 that repeats in the log and appears to cause the autoagora container to restart. Maybe another exception backoff required?

I confirmed that the indexer-service counters are generally available (via the datasource I use to scrape from indexer-service.)

```2022-11-06 13:14:54,891 - root - ERROR - Giving up subgraph_query_count(...) after 7 tries (autoagora.query_metrics.HTTPError: 404)
2022-11-06 13:14:54,892 - root - ERROR - price_bandit_loop error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/autoagora/price_multiplier.py", line 83, in price_bandit_loop
    queries_per_second = await environment.queries_per_second(60)
  File "/usr/local/lib/python3.8/site-packages/autoagora/subgraph_wrapper.py", line 32, in queries_per_second
    query_count_1 = await subgraph_query_count(self.subgraph)
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/autoagora/query_metrics.py", line 65, in subgraph_query_count
    raise HTTPError(response.status)
autoagora.query_metrics.HTTPError: 404```

**Comment by aasseman** [comment]
Have you double-checked `INDEXER_SERVICE_METRICS_ENDPOINT`? It should point to the `indexer-service`'s prometheus endpoint.

**Comment by cryptovestor21** [comment]
After some testing, it was evident I was missing `/metrics` path on the end of this var. No errors since adding it to the var. Thank you @aasseman !

**Comment by aasseman** [comment]
AA probably needs more explicit error messages!
